### PR TITLE
refactor!: simplify the module, tests, and remove old interface

### PR DESCRIPTION
**Pull request by JustinBeckwith**
**BREAKING CHANGE**: The `testInstallation` method has been removed.  Please migrate to the `packNTest` method instead.

This PR has a few changes:
- Remove the deprecated `testInstallation` method
- Drastically simplify the tests by using fixtures, and more system-test style
- Switch to using `execa` for process spawning

This change is a precursor to more changes that will unblock failing tests in other Google owned modules.

### CODE REVIEW

**Comment by JustinBeckwith** [comment]
Not quite ready yet :) My testing strategy was a tad naive ...

**Comment by JustinBeckwith** [comment]
One of the changes in here is that it passes all process failures up in the Error returned to the client :)

**Comment by JustinBeckwith** [comment]
@alexander-fenster I know we had a way to do `npm link` with Circle CI, I just can't remember how to do it. 

@bcoe @soldair I made these changes to the tests, and I'm not sure if it was a good idea or not.  I didn't like how previously, the unit tests were held together by mocking out the universe, and leaving a very small amount of the code under actual test. I also didn't like how we had to thread injectables throughout the sources.  The way the tests in this PR work:
- They are end to end tests.  
- There are fixture directories, with full apps with their own tests
- Those full apps `npm link` to `pack-n-play`, and run their own tests

The good part:
- We are covering the actual usage of the module
- There is no code jammed inside src/ purely for the benefit of tests

The bad part:
- The tests are sloooooooooooow (like 90-120 seconds slow)
- They are also kinda hard to understand the first time you look at it

What are others thoughts here?

**Comment by alexander-fenster** [comment]
@JustinBeckwith To make `npm link` work for non-root user, we used to set an environment variable:

```yaml
environment:
  NPM_CONFIG_PREFIX: /home/node/.npm-global
```

**Pull request merged**
